import type { SceneConfig, SlideConfig, Timeframe } from '../types';

const weekly: SlideConfig[] = [
  {
    id: 'shared-metrics',
    title: '共享 KPI',
    subtitle: '双方认可的基准数据',
    component: 'shared-metrics',
    section: '开场',
    revealSteps: 3,
    duration: 90,
    presenterNotes: '展示双方共同认可的数据基准：注册总数/付费总数/本周收入，确认数字无争议。',
  },
  {
    id: 'funnel-ownership',
    title: '漏斗所有权',
    subtitle: '运营（蓝）vs 业务（橙）责任边界',
    component: 'funnel-ownership',
    section: '数据分析',
    revealSteps: 4,
    duration: 90,
    presenterNotes: '明确每层漏斗的责任归属：外呼/跟进（运营），转化/关单（业务），共同负责层高亮。',
  },
  {
    id: 'leads-handoff',
    title: 'Leads 交接质量',
    subtitle: '本周交接数据质量审查',
    component: 'leads-handoff',
    section: '数据分析',
    revealSteps: 3,
    duration: 90,
    presenterNotes: '交接 leads 数量、质量评分（窄口/宽口比例）、交接时效，双方确认数据。',
  },
  {
    id: 'impact-attribution',
    title: '损失归因',
    subtitle: '本周损失由谁负责',
    component: 'impact-attribution',
    section: '数据分析',
    revealSteps: 3,
    duration: 90,
    presenterNotes: '用数据说话：本周损失中，运营侧原因（外呼不足/跟进缺失）vs 业务侧原因（转化率低）各占多少。',
  },
  {
    id: 'joint-action',
    title: '联合行动承诺',
    subtitle: '本次会议达成的共识',
    component: 'joint-action',
    section: '结论',
    revealSteps: 3,
    duration: 90,
    presenterNotes: '运营承诺：本周提升什么。业务承诺：本周改善什么。双方签字的量化目标。',
  },
];

const monthly: SlideConfig[] = [
  {
    id: 'shared-metrics',
    title: '共享 KPI',
    subtitle: '本月基准数据确认',
    component: 'shared-metrics',
    section: '开场',
    revealSteps: 3,
    duration: 90,
    presenterNotes: '展示本月双方共同认可的基准数据，确认无争议后进入分析环节。',
  },
  {
    id: 'funnel-ownership',
    title: '漏斗所有权',
    subtitle: '月度漏斗责任边界',
    component: 'funnel-ownership',
    section: '数据分析',
    revealSteps: 4,
    duration: 120,
    presenterNotes: '本月每层漏斗表现，按责任归属分色显示，清晰展示各方贡献和缺口。',
  },
  {
    id: 'leads-handoff',
    title: 'Leads 交接质量',
    subtitle: '月度交接质量审查',
    component: 'leads-handoff',
    section: '数据分析',
    revealSteps: 3,
    duration: 90,
    presenterNotes: '本月 leads 交接量/质量/时效数据，与上月对比，标注改善和退步项。',
  },
  {
    id: 'conversion-accountability',
    title: '转化率责任归属',
    subtitle: '谁的转化率出了问题',
    component: 'conversion-accountability',
    section: '数据分析',
    revealSteps: 4,
    duration: 120,
    presenterNotes: '注册→付费转化率按 CC/SS/LP 分解，标注责任归属，数据驱动而非主观判断。',
  },
  {
    id: 'impact-attribution',
    title: '损失归因',
    subtitle: '本月损失量化归因',
    component: 'impact-attribution',
    section: '数据分析',
    revealSteps: 4,
    duration: 120,
    presenterNotes: '本月总损失 $X，其中运营侧损失 $Y（原因），业务侧损失 $Z（原因），共同责任 $W。',
  },
  {
    id: 'what-if-simulation',
    title: '改进模拟',
    subtitle: '如果各方改善 X%',
    component: 'what-if-simulation',
    section: '数据分析',
    revealSteps: 3,
    duration: 90,
    presenterNotes: '如果运营侧跟进率提升 10% + 业务侧转化率提升 5%，合计可增加 $Y 收入。',
  },
  {
    id: 'joint-action',
    title: '联合行动承诺',
    subtitle: '下月双方承诺事项',
    component: 'joint-action',
    section: '结论',
    revealSteps: 3,
    duration: 90,
    presenterNotes: '运营方承诺 3 条具体改进（量化），业务方承诺 3 条具体改进（量化），下月会议验收。',
  },
  {
    id: 'summary',
    title: '会议总结',
    subtitle: '共识记录',
    component: 'meeting-summary',
    section: '结论',
    revealSteps: 2,
    duration: 60,
    presenterNotes: '记录本次会议达成的共识，数据争议的处理方式，下次会议时间和议程。',
  },
];

const quarterly: SlideConfig[] = [
  {
    id: 'shared-metrics',
    title: '季度共享 KPI',
    subtitle: '三个月基准数据',
    component: 'shared-metrics',
    section: '开场',
    revealSteps: 3,
    duration: 90,
    presenterNotes: '三个月双方认可的基准数据，季度总额和月度分布，确认数字无争议。',
  },
  {
    id: 'funnel-ownership',
    title: '漏斗所有权',
    subtitle: '季度责任分析',
    component: 'funnel-ownership',
    section: '数据分析',
    revealSteps: 4,
    duration: 120,
    presenterNotes: '季度各层漏斗责任归属，三个月责任边界变化，识别系统性问题。',
  },
  {
    id: 'leads-handoff',
    title: 'Leads 交接质量',
    subtitle: '季度交接质量趋势',
    component: 'leads-handoff',
    section: '数据分析',
    revealSteps: 3,
    duration: 90,
    presenterNotes: '三个月交接质量趋势，改善措施效果评估，下季度质量目标设定。',
  },
  {
    id: 'conversion-accountability',
    title: '转化率责任归属',
    subtitle: '季度转化分析',
    component: 'conversion-accountability',
    section: '数据分析',
    revealSteps: 4,
    duration: 120,
    presenterNotes: '季度转化率变化，责任归属演变，改善和退步的系统性原因。',
  },
  {
    id: 'impact-attribution',
    title: '损失归因',
    subtitle: '季度损失量化',
    component: 'impact-attribution',
    section: '数据分析',
    revealSteps: 4,
    duration: 120,
    presenterNotes: '季度总损失归因，各方责任量化，累计机会损失分析。',
  },
  {
    id: 'what-if-simulation',
    title: '改进模拟',
    subtitle: '下季度改善预测',
    component: 'what-if-simulation',
    section: '数据分析',
    revealSteps: 3,
    duration: 90,
    presenterNotes: '基于本季数据，模拟下季度双方各改善目标量可带来的收入增量。',
  },
  {
    id: 'joint-action',
    title: '季度联合行动',
    subtitle: '下季度协同承诺',
    component: 'joint-action',
    section: '结论',
    revealSteps: 3,
    duration: 90,
    presenterNotes: '双方下季度各 3 个重点改进方向，联合里程碑，季度末验收标准。',
  },
  {
    id: 'summary',
    title: '季度复盘总结',
    subtitle: '共识记录与下季计划',
    component: 'meeting-summary',
    section: '结论',
    revealSteps: 2,
    duration: 60,
    presenterNotes: '本季复盘共识，下季度联合目标，合作机制优化建议。',
  },
  {
    id: 'conversion-accountability',
    title: '协作机制优化',
    subtitle: '流程改进建议',
    component: 'conversion-accountability',
    section: '结论',
    revealSteps: 2,
    duration: 60,
    presenterNotes: '本季暴露的协作痛点，下季度流程优化方案，责任边界重新对齐。',
  },
  {
    id: 'what-if-simulation',
    title: '年度目标对齐',
    subtitle: '本季进展与年度目标差距',
    component: 'what-if-simulation',
    section: '结论',
    revealSteps: 2,
    duration: 60,
    presenterNotes: '本季达成情况对年度目标的影响，剩余季度需要的合力，双方资源承诺。',
  },
];

// crosscheck 不支持 daily 和 yearly，返回空数组（运行时通过 availableTimeframes 过滤）
const unsupported: SlideConfig[] = [];

export const crosscheckScene: SceneConfig = {
  id: 'crosscheck',
  label: '对等会议',
  description: '与业务总监对等会议，攻防结构，聚焦责任归属与联合行动',
  icon: 'Users',
  availableTimeframes: ['weekly', 'monthly', 'quarterly'] as Timeframe[],
  slides: {
    daily: unsupported,
    weekly,
    monthly,
    quarterly,
    yearly: unsupported,
  },
};
