import type { SceneConfig, SlideConfig } from '../types';

const daily: SlideConfig[] = [
  {
    id: 'executive-summary',
    title: '今日快照',
    subtitle: '核心 KPI 实时状态',
    component: 'executive-summary',
    section: '开场',
    revealSteps: 3,
    duration: 90,
    presenterNotes: '展示今日注册/付费/收入三项核心数据，与昨日对比，标注异常。',
  },
  {
    id: 'key-changes',
    title: '关键变化',
    subtitle: '今日与昨日对比',
    component: 'key-changes',
    section: '数据分析',
    revealSteps: 2,
    duration: 60,
    presenterNotes: '指出今日最显著的正负变化，每项变化附带可能原因。',
  },
  {
    id: 'action-items',
    title: '今日行动项',
    subtitle: '需要决策或跟进的事项',
    component: 'action-items',
    section: '结论',
    revealSteps: 3,
    duration: 60,
    presenterNotes: '列出需要 GM 批准或知晓的行动项，每项说明时限和责任人。',
  },
];

const weekly: SlideConfig[] = [
  {
    id: 'executive-summary',
    title: '本周总结',
    subtitle: '周度 KPI 完成情况',
    component: 'executive-summary',
    section: '开场',
    revealSteps: 3,
    duration: 90,
    presenterNotes: '本周 vs 上周核心指标对比，进度百分比，时间进度差。',
  },
  {
    id: 'wow-comparison',
    title: '周环比分析',
    subtitle: 'WoW 趋势',
    component: 'wow-comparison',
    section: '数据分析',
    revealSteps: 2,
    duration: 90,
    presenterNotes: '展示过去 4 周趋势线，标注上升/下降/波动趋势。',
  },
  {
    id: 'funnel-overview',
    title: '漏斗进展',
    subtitle: '注册→付费→收入转化',
    component: 'funnel-overview',
    section: '数据分析',
    revealSteps: 4,
    duration: 90,
    presenterNotes: '每层漏斗的绝对数和转化率，标注最大漏损点。',
  },
  {
    id: 'risk-radar',
    title: '风险预警',
    subtitle: '本周异常与红色信号',
    component: 'risk-radar',
    section: '数据分析',
    revealSteps: 2,
    duration: 60,
    presenterNotes: '列出 2-3 个最高风险项，每项附带严重程度和建议应对措施。',
  },
  {
    id: 'action-items',
    title: '下周计划',
    subtitle: '行动计划与优先级',
    component: 'action-items',
    section: '结论',
    revealSteps: 3,
    duration: 60,
    presenterNotes: '下周重点工作，需要 GM 资源支持的事项，量化预期收益。',
  },
];

const monthly: SlideConfig[] = [
  {
    id: 'executive-summary',
    title: '高管摘要',
    subtitle: '月度 KPI 快照',
    component: 'executive-summary',
    section: '开场',
    revealSteps: 3,
    duration: 120,
    presenterNotes: '一句话结论：本月整体表现。然后展示注册/付费/收入三项与目标对比，用状态灯（🟢🟡🔴）标注。',
  },
  {
    id: 'revenue-analysis',
    title: '收入分析',
    subtitle: 'ROI + 业绩归因',
    component: 'revenue-analysis',
    section: '数据分析',
    revealSteps: 4,
    duration: 120,
    presenterNotes: '转介绍收入构成、ROI 成本效益、渠道贡献度。重点：CC 新单转介绍是核心口径。',
  },
  {
    id: 'funnel-overview',
    title: '全漏斗概览',
    subtitle: '从有效学员到付费',
    component: 'funnel-overview',
    section: '数据分析',
    revealSteps: 5,
    duration: 120,
    presenterNotes: '触达率→参与率→打卡率→注册→付费，每层转化率与目标对比，最大漏损点用红色标注。',
  },
  {
    id: 'team-performance',
    title: '团队绩效排名',
    subtitle: 'CC/SS/LP 综合得分',
    component: 'team-performance',
    section: '数据分析',
    revealSteps: 3,
    duration: 90,
    presenterNotes: '展示前 3 名和后 3 名，突出头尾差距，说明后进者的主要短板。',
  },
  {
    id: 'risk-radar',
    title: '风险与异常',
    subtitle: '5-Why 根因分析',
    component: 'risk-radar',
    section: '数据分析',
    revealSteps: 3,
    duration: 90,
    presenterNotes: '本月最大风险点的 5-Why 根因链，量化影响（损失 $X）。',
  },
  {
    id: 'impact-simulation',
    title: '影响链模拟',
    subtitle: 'What-if 改进场景',
    component: 'impact-simulation',
    section: '数据分析',
    revealSteps: 3,
    duration: 90,
    presenterNotes: '展示：如果触达率提升 10%，可增加多少注册/付费/收入。数字要具体到 $。',
  },
  {
    id: 'strategic-recommendation',
    title: '战略建议',
    subtitle: 'SCQA 结构',
    component: 'strategic-recommendation',
    section: '结论',
    revealSteps: 4,
    duration: 120,
    presenterNotes: '背景→冲突→疑问→答案。给出 3 条可执行建议，每条附带预期量化收益和所需资源。',
  },
];

const quarterly: SlideConfig[] = [
  {
    id: 'executive-summary',
    title: '季度总结',
    subtitle: 'Q 度整体表现',
    component: 'executive-summary',
    section: '开场',
    revealSteps: 3,
    duration: 120,
    presenterNotes: '季度三个月 KPI 完成率，与上季度对比，标注最大改善和最大退步。',
  },
  {
    id: 'trend-analysis',
    title: '趋势分析',
    subtitle: '过去 3 个月走势',
    component: 'trend-analysis',
    section: '数据分析',
    revealSteps: 3,
    duration: 120,
    presenterNotes: '三个月趋势图，标注拐点、突变点及其背后原因。',
  },
  {
    id: 'revenue-deep-dive',
    title: '收入深度分析',
    subtitle: '渠道/SKU/团队贡献',
    component: 'revenue-deep-dive',
    section: '数据分析',
    revealSteps: 4,
    duration: 120,
    presenterNotes: '按渠道、套餐、团队三维度分解收入，标注增量来源和损失来源。',
  },
  {
    id: 'team-performance',
    title: '团队绩效',
    subtitle: '季度综合排名变化',
    component: 'team-performance',
    section: '数据分析',
    revealSteps: 3,
    duration: 90,
    presenterNotes: '对比本季三个月排名变化，标注进步最快和退步最快的人员。',
  },
  {
    id: 'impact-simulation',
    title: '影响链分析',
    subtitle: '效率 gap 的量化损失',
    component: 'impact-simulation',
    section: '数据分析',
    revealSteps: 3,
    duration: 90,
    presenterNotes: '本季最大的效率短板是什么，损失了多少收入，改善方向。',
  },
  {
    id: 'cohort-analysis',
    title: 'Cohort 留存',
    subtitle: '转介绍用户生命周期',
    component: 'cohort-analysis',
    section: '数据分析',
    revealSteps: 3,
    duration: 90,
    presenterNotes: '各月入组用户在 30/60/90 天后的留存率，标注留存最好的入组月及共同特征。',
  },
  {
    id: 'strategic-recommendation',
    title: '季度策略',
    subtitle: '下季度重点方向',
    component: 'strategic-recommendation',
    section: '结论',
    revealSteps: 4,
    duration: 120,
    presenterNotes: '基于本季数据给出 3-5 条下季度战略方向，每条量化预期收益。',
  },
  {
    id: 'resource-request',
    title: '资源需求',
    subtitle: '支持下季增长的资源申请',
    component: 'resource-request',
    section: '结论',
    revealSteps: 3,
    duration: 90,
    presenterNotes: '明确列出需要 GM 批准的资源（人力/预算/工具），附带 ROI 测算。',
  },
];

const yearly: SlideConfig[] = [
  {
    id: 'executive-summary',
    title: '年度总结',
    subtitle: '全年核心指标',
    component: 'executive-summary',
    section: '开场',
    revealSteps: 3,
    duration: 120,
    presenterNotes: '全年 KPI 完成情况，与年度目标对比，三句话总结全年成就和挑战。',
  },
  {
    id: 'yoy-comparison',
    title: '同比分析',
    subtitle: '与上年同期对比',
    component: 'yoy-comparison',
    section: '数据分析',
    revealSteps: 3,
    duration: 120,
    presenterNotes: '核心 KPI 同比增长率，标注超预期和低于预期的指标，分析原因。',
  },
  {
    id: 'trend-analysis',
    title: '全年趋势',
    subtitle: '12 个月走势',
    component: 'trend-analysis',
    section: '数据分析',
    revealSteps: 3,
    duration: 120,
    presenterNotes: '月度趋势图，标注全年高峰、低谷、关键拐点及背后事件。',
  },
  {
    id: 'revenue-deep-dive',
    title: '收入深度分析',
    subtitle: '全年收入结构',
    component: 'revenue-deep-dive',
    section: '数据分析',
    revealSteps: 4,
    duration: 120,
    presenterNotes: '全年收入按渠道/套餐/季度分解，标注结构变化和增量驱动因素。',
  },
  {
    id: 'team-evolution',
    title: '团队成长',
    subtitle: '全年 CC/SS/LP 能力进化',
    component: 'team-evolution',
    section: '数据分析',
    revealSteps: 3,
    duration: 90,
    presenterNotes: '团队规模变化、人均产出变化、前 20% vs 后 20% 差距变化。',
  },
  {
    id: 'cohort-analysis',
    title: '留存分析',
    subtitle: '转介绍用户生命周期',
    component: 'cohort-analysis',
    section: '数据分析',
    revealSteps: 3,
    duration: 90,
    presenterNotes: '全年各季度入组用户留存率矩阵，标注留存改善或下降趋势。',
  },
  {
    id: 'stage-evaluation',
    title: '阶段评估',
    subtitle: '转介绍运营演化阶段',
    component: 'stage-evaluation',
    section: '数据分析',
    revealSteps: 3,
    duration: 90,
    presenterNotes: '判断当前处于：基础启动/科学运营/系统思维哪个阶段，升级条件是什么。',
  },
  {
    id: 'strategic-recommendation',
    title: '年度战略',
    subtitle: '明年战略方向',
    component: 'strategic-recommendation',
    section: '结论',
    revealSteps: 4,
    duration: 120,
    presenterNotes: '基于今年数据给出明年 3 大战略方向，每个方向附带可量化的成功指标。',
  },
  {
    id: 'resource-request',
    title: '资源规划',
    subtitle: '明年预算与人力规划',
    component: 'resource-request',
    section: '结论',
    revealSteps: 3,
    duration: 90,
    presenterNotes: '明年增长目标 → 所需资源 → ROI 测算 → 请求 GM 批准的核心资源。',
  },
];

export const gmScene: SceneConfig = {
  id: 'gm',
  label: 'GM 汇报',
  description: '向 GM 汇报，战略层面，聚焦核心 KPI 与战略方向',
  icon: 'TrendingUp',
  availableTimeframes: ['daily', 'weekly', 'monthly', 'quarterly', 'yearly'],
  slides: {
    daily,
    weekly,
    monthly,
    quarterly,
    yearly,
  },
};
