import type { SceneConfig, SlideConfig } from '../types';

const daily: SlideConfig[] = [
  {
    id: 'executive-summary',
    title: '运营指标摘要',
    subtitle: '今日执行情况',
    component: 'executive-summary',
    section: '开场',
    revealSteps: 3,
    duration: 90,
    presenterNotes: '今日外呼/接通/跟进执行量，与日均目标对比。',
  },
  {
    id: 'outreach-execution',
    title: '外呼执行情况',
    subtitle: '今日触达数据',
    component: 'outreach-execution',
    section: '数据分析',
    revealSteps: 2,
    duration: 60,
    presenterNotes: '外呼数/接通数/有效接通数，按 CC 分组，标注未完成配额的人员。',
  },
  {
    id: 'followup-alert',
    title: '跟进预警',
    subtitle: '零跟进或超期跟进学员',
    component: 'followup-alert',
    section: '数据分析',
    revealSteps: 2,
    duration: 60,
    presenterNotes: '今日需要重点跟进但尚未跟进的学员列表，按优先级排序。',
  },
  {
    id: 'action-plan',
    title: '今日行动',
    subtitle: '需要运营总监关注的事项',
    component: 'action-plan',
    section: '结论',
    revealSteps: 2,
    duration: 60,
    presenterNotes: '今日需要总监决策或资源协调的事项，明确时限和责任人。',
  },
];

const weekly: SlideConfig[] = [
  {
    id: 'executive-summary',
    title: '运营指标摘要',
    subtitle: '本周执行总览',
    component: 'executive-summary',
    section: '开场',
    revealSteps: 3,
    duration: 90,
    presenterNotes: '本周外呼/跟进/注册/付费与目标对比，状态灯标注。',
  },
  {
    id: 'outreach-execution',
    title: '外呼执行情况',
    subtitle: '本周触达数据',
    component: 'outreach-execution',
    section: '数据分析',
    revealSteps: 3,
    duration: 90,
    presenterNotes: '本周 vs 上周外呼数量和质量对比，标注改善和下滑的 CC。',
  },
  {
    id: 'trial-followup',
    title: '体验课跟进',
    subtitle: '课前/课后跟进完成率',
    component: 'trial-followup',
    section: '数据分析',
    revealSteps: 2,
    duration: 60,
    presenterNotes: '预约课前跟进率/预约课后跟进率/付费后跟进率，与目标对比。',
  },
  {
    id: 'funnel-detail',
    title: '漏斗详情',
    subtitle: '本周转化链路',
    component: 'funnel-detail',
    section: '数据分析',
    revealSteps: 4,
    duration: 90,
    presenterNotes: '每层漏斗本周表现，重点分析最大漏损层的原因。',
  },
  {
    id: 'followup-alert',
    title: '跟进预警',
    subtitle: '本周零跟进/高风险学员',
    component: 'followup-alert',
    section: '数据分析',
    revealSteps: 2,
    duration: 60,
    presenterNotes: '本周识别的零跟进学员数量，损失潜力估算，处理建议。',
  },
  {
    id: 'kpi-north-star',
    title: '北极星 KPI',
    subtitle: '本周核心指标进展',
    component: 'kpi-north-star',
    section: '数据分析',
    revealSteps: 2,
    duration: 60,
    presenterNotes: '转介绍业绩（CC 新单）进度，时间进度差，每日需完成量。',
  },
  {
    id: 'action-plan',
    title: '下周行动计划',
    subtitle: '执行计划与资源需求',
    component: 'action-plan',
    section: '结论',
    revealSteps: 3,
    duration: 90,
    presenterNotes: '下周 3 个重点执行动作，每个附带负责人、时限和预期量化收益。',
  },
];

const monthly: SlideConfig[] = [
  {
    id: 'executive-summary',
    title: '运营指标摘要',
    subtitle: '月度执行综述',
    component: 'executive-summary',
    section: '开场',
    revealSteps: 3,
    duration: 120,
    presenterNotes: '本月 12 项核心运营指标完成情况，用状态灯（🟢🟡🔴）一图展示。',
  },
  {
    id: 'outreach-execution',
    title: '外呼执行情况',
    subtitle: '月度触达深度分析',
    component: 'outreach-execution',
    section: '数据分析',
    revealSteps: 3,
    duration: 120,
    presenterNotes: '外呼总量、接通率、有效接通率按 CC 分解，热力图展示时段分布。',
  },
  {
    id: 'trial-followup',
    title: '体验课跟进',
    subtitle: '全链路跟进情况',
    component: 'trial-followup',
    section: '数据分析',
    revealSteps: 3,
    duration: 90,
    presenterNotes: '付费前跟进/预约课前/预约课后/付费后四个跟进节点完成率，缺口分析。',
  },
  {
    id: 'funnel-detail',
    title: '漏斗详情',
    subtitle: '月度全漏斗分析',
    component: 'funnel-detail',
    section: '数据分析',
    revealSteps: 4,
    duration: 120,
    presenterNotes: '有效学员→触达→参与→打卡→注册→付费，每层数量和转化率，5-Why 根因分析。',
  },
  {
    id: 'team-ranking',
    title: 'CC 18维排名',
    subtitle: '过程×结果×效率综合得分',
    component: 'team-ranking',
    section: '数据分析',
    revealSteps: 3,
    duration: 120,
    presenterNotes: '18 个维度综合排名，展示前 5 名和后 5 名，说明排名依据和改进方向。',
  },
  {
    id: 'channel-breakdown',
    title: '渠道分析',
    subtitle: '各渠道业绩贡献',
    component: 'channel-breakdown',
    section: '数据分析',
    revealSteps: 3,
    duration: 90,
    presenterNotes: '转介绍渠道 vs 市场渠道业绩，环比变化，渠道效率对比。',
  },
  {
    id: 'followup-alert',
    title: '跟进预警',
    subtitle: '本月高风险学员分析',
    component: 'followup-alert',
    section: '数据分析',
    revealSteps: 2,
    duration: 60,
    presenterNotes: '本月零跟进学员数量和损失估算，处理结果追踪，改进措施。',
  },
  {
    id: 'kpi-north-star',
    title: '北极星 KPI',
    subtitle: '月度核心指标深度',
    component: 'kpi-north-star',
    section: '数据分析',
    revealSteps: 3,
    duration: 90,
    presenterNotes: '转介绍业绩完成率，时间进度差，剩余日均需求，效率提升需求百分比。',
  },
  {
    id: 'outreach-gap',
    title: '外呼缺口',
    subtitle: '目标 vs 实际缺口分析',
    component: 'outreach-gap',
    section: '数据分析',
    revealSteps: 2,
    duration: 60,
    presenterNotes: '按 CC 展示外呼配额缺口，换算为潜在错失的注册和收入。',
  },
  {
    id: 'cohort-analysis',
    title: 'Cohort 分析',
    subtitle: '转介绍用户留存',
    component: 'cohort-analysis',
    section: '数据分析',
    revealSteps: 3,
    duration: 90,
    presenterNotes: '本月入组用户 30/60/90 天预测留存，与上月入组对比。',
  },
  {
    id: 'resource-request',
    title: '资源需求',
    subtitle: '完成目标所需支持',
    component: 'resource-request',
    section: '结论',
    revealSteps: 3,
    duration: 90,
    presenterNotes: '明确列出需要总监协调的资源（人力/工具/流程/预算），附带不批准的损失估算。',
  },
  {
    id: 'action-plan',
    title: '行动计划',
    subtitle: '下月执行路线图',
    component: 'action-plan',
    section: '结论',
    revealSteps: 3,
    duration: 90,
    presenterNotes: '下月 5 大执行重点，每项附带 KPI 指标、负责人、时限、预期改善量。',
  },
];

const quarterly: SlideConfig[] = [
  {
    id: 'executive-summary',
    title: '运营指标摘要',
    subtitle: '季度执行总览',
    component: 'executive-summary',
    section: '开场',
    revealSteps: 3,
    duration: 120,
    presenterNotes: '季度三个月运营指标完成情况，按月拆解，标注进步和退步的月份。',
  },
  {
    id: 'outreach-execution',
    title: '外呼执行情况',
    subtitle: '季度触达趋势',
    component: 'outreach-execution',
    section: '数据分析',
    revealSteps: 3,
    duration: 90,
    presenterNotes: '三个月外呼量趋势，接通率变化，CC 执行能力成长曲线。',
  },
  {
    id: 'trial-followup',
    title: '体验课跟进',
    subtitle: '季度跟进质量分析',
    component: 'trial-followup',
    section: '数据分析',
    revealSteps: 3,
    duration: 90,
    presenterNotes: '四个跟进节点的季度完成率变化，改善最多和最少的节点。',
  },
  {
    id: 'funnel-detail',
    title: '漏斗详情',
    subtitle: '季度漏斗演变',
    component: 'funnel-detail',
    section: '数据分析',
    revealSteps: 4,
    duration: 120,
    presenterNotes: '三个月漏斗对比，每层转化率变化，改善和恶化的层次分析。',
  },
  {
    id: 'team-ranking',
    title: '团队排名变化',
    subtitle: '季度 CC 成长分析',
    component: 'team-ranking',
    section: '数据分析',
    revealSteps: 3,
    duration: 90,
    presenterNotes: '三个月排名变化矩阵，进步最快的 CC（奖励依据），退步最大的 CC（辅导依据）。',
  },
  {
    id: 'channel-breakdown',
    title: '渠道分析',
    subtitle: '季度渠道趋势',
    component: 'channel-breakdown',
    section: '数据分析',
    revealSteps: 3,
    duration: 90,
    presenterNotes: '各渠道季度贡献变化，转介绍渠道占比趋势，渠道效率对比。',
  },
  {
    id: 'followup-alert',
    title: '跟进预警',
    subtitle: '季度预警统计',
    component: 'followup-alert',
    section: '数据分析',
    revealSteps: 2,
    duration: 60,
    presenterNotes: '季度累计零跟进学员数量和损失估算，系统改进效果追踪。',
  },
  {
    id: 'kpi-north-star',
    title: '北极星 KPI',
    subtitle: '季度核心指标',
    component: 'kpi-north-star',
    section: '数据分析',
    revealSteps: 3,
    duration: 90,
    presenterNotes: '季度转介绍业绩完成率，三个月进度曲线，季度差额分解。',
  },
  {
    id: 'outreach-gap',
    title: '外呼缺口',
    subtitle: '季度缺口分析',
    component: 'outreach-gap',
    section: '数据分析',
    revealSteps: 2,
    duration: 60,
    presenterNotes: '季度累计外呼缺口，换算为损失的注册和收入，系统根因分析。',
  },
  {
    id: 'cohort-analysis',
    title: 'Cohort 分析',
    subtitle: '季度留存对比',
    component: 'cohort-analysis',
    section: '数据分析',
    revealSteps: 3,
    duration: 90,
    presenterNotes: '三个月各入组留存率矩阵，黄金窗口期识别，留存改善措施效果评估。',
  },
  {
    id: 'resource-request',
    title: '资源需求',
    subtitle: '下季度资源申请',
    component: 'resource-request',
    section: '结论',
    revealSteps: 3,
    duration: 90,
    presenterNotes: '下季度增长目标 → 所需资源 → ROI 测算，每项资源附带不批准的机会损失。',
  },
  {
    id: 'action-plan',
    title: '季度行动计划',
    subtitle: '下季度执行路线图',
    component: 'action-plan',
    section: '结论',
    revealSteps: 3,
    duration: 90,
    presenterNotes: '下季度 3 大执行重点，里程碑节点，每阶段 KPI 目标。',
  },
  {
    id: 'channel-breakdown',
    title: '渠道优化建议',
    subtitle: '下季度渠道策略',
    component: 'channel-breakdown',
    section: '结论',
    revealSteps: 2,
    duration: 60,
    presenterNotes: '基于本季渠道数据，建议下季度渠道资源分配策略。',
  },
  {
    id: 'team-ranking',
    title: '人才发展计划',
    subtitle: '基于排名的培训规划',
    component: 'team-ranking',
    section: '结论',
    revealSteps: 2,
    duration: 60,
    presenterNotes: '下季度 Top 人才激励方案，后进人员培训计划，新人成长路径。',
  },
];

const yearly: SlideConfig[] = [
  {
    id: 'executive-summary',
    title: '年度运营综述',
    subtitle: '全年执行情况',
    component: 'executive-summary',
    section: '开场',
    revealSteps: 3,
    duration: 120,
    presenterNotes: '全年 12 个月核心运营指标完成情况汇总，三句话总结全年执行亮点和不足。',
  },
  {
    id: 'outreach-execution',
    title: '外呼全年分析',
    subtitle: '外呼能力年度成长',
    component: 'outreach-execution',
    section: '数据分析',
    revealSteps: 3,
    duration: 120,
    presenterNotes: '12 个月外呼量/接通率/有效接通率趋势，能力提升量化。',
  },
  {
    id: 'trial-followup',
    title: '跟进体系全年',
    subtitle: '四节点跟进质量演变',
    component: 'trial-followup',
    section: '数据分析',
    revealSteps: 3,
    duration: 90,
    presenterNotes: '全年四个跟进节点完成率变化，标注实施改进措施后的效果。',
  },
  {
    id: 'funnel-detail',
    title: '年度漏斗演变',
    subtitle: '全年转化率变化',
    component: 'funnel-detail',
    section: '数据分析',
    revealSteps: 4,
    duration: 120,
    presenterNotes: '12 个月各层漏斗转化率变化，标注全年最高/最低月份，原因分析。',
  },
  {
    id: 'team-ranking',
    title: '团队年度评估',
    subtitle: 'CC 全年综合表现',
    component: 'team-ranking',
    section: '数据分析',
    revealSteps: 3,
    duration: 90,
    presenterNotes: '全年平均综合得分排名，进步最快和退步最大的人员，年度优秀员工依据。',
  },
  {
    id: 'channel-breakdown',
    title: '渠道年度分析',
    subtitle: '渠道结构演变',
    component: 'channel-breakdown',
    section: '数据分析',
    revealSteps: 3,
    duration: 90,
    presenterNotes: '各渠道全年贡献演变，转介绍占比提升或下降趋势，渠道效率成熟度评估。',
  },
  {
    id: 'followup-alert',
    title: '跟进预警年度',
    subtitle: '全年预警处理情况',
    component: 'followup-alert',
    section: '数据分析',
    revealSteps: 2,
    duration: 60,
    presenterNotes: '全年零跟进学员数量趋势，系统改进效果，未来预防措施。',
  },
  {
    id: 'kpi-north-star',
    title: '北极星 KPI 年度',
    subtitle: '全年核心指标达成',
    component: 'kpi-north-star',
    section: '数据分析',
    revealSteps: 3,
    duration: 90,
    presenterNotes: '全年转介绍业绩总额，与年初目标对比，超额或缺口原因分析。',
  },
  {
    id: 'outreach-gap',
    title: '年度外呼缺口',
    subtitle: '全年缺口与机会损失',
    component: 'outreach-gap',
    section: '数据分析',
    revealSteps: 2,
    duration: 60,
    presenterNotes: '全年累计外呼缺口，换算为机会损失，明年系统性解决方案。',
  },
  {
    id: 'cohort-analysis',
    title: '年度 Cohort',
    subtitle: '各季度用户留存矩阵',
    component: 'cohort-analysis',
    section: '数据分析',
    revealSteps: 3,
    duration: 90,
    presenterNotes: '四个季度各入组队列留存率全矩阵，留存最佳季度特征分析，明年留存策略。',
  },
  {
    id: 'resource-request',
    title: '明年资源规划',
    subtitle: '预算与人力申请',
    component: 'resource-request',
    section: '结论',
    revealSteps: 3,
    duration: 90,
    presenterNotes: '明年增长目标 → 所需资源清单 → 每项 ROI 测算 → 优先级排序。',
  },
  {
    id: 'action-plan',
    title: '明年行动计划',
    subtitle: '年度执行路线图',
    component: 'action-plan',
    section: '结论',
    revealSteps: 3,
    duration: 90,
    presenterNotes: '明年 4 个季度执行重点，每季度里程碑，全年 KPI 目标拆解到季度。',
  },
  {
    id: 'team-ranking',
    title: '团队发展规划',
    subtitle: '明年人才培养计划',
    component: 'team-ranking',
    section: '结论',
    revealSteps: 2,
    duration: 60,
    presenterNotes: '明年团队规模规划，人才梯队建设，培训体系完善计划。',
  },
  {
    id: 'channel-breakdown',
    title: '渠道明年策略',
    subtitle: '渠道资源优化',
    component: 'channel-breakdown',
    section: '结论',
    revealSteps: 2,
    duration: 60,
    presenterNotes: '基于全年渠道表现，明年渠道资源分配策略和渠道多元化计划。',
  },
  {
    id: 'kpi-north-star',
    title: '明年北极星 KPI',
    subtitle: '目标设定与对齐',
    component: 'kpi-north-star',
    section: '结论',
    revealSteps: 3,
    duration: 90,
    presenterNotes: '明年转介绍业绩目标，拆解到月度/季度，关键前置指标目标（漏斗各层）。',
  },
  {
    id: 'outreach-execution',
    title: '外呼能力规划',
    subtitle: '明年外呼体系升级',
    component: 'outreach-execution',
    section: '结论',
    revealSteps: 2,
    duration: 60,
    presenterNotes: '明年外呼目标，系统工具升级计划，外呼能力培训计划。',
  },
  {
    id: 'action-plan',
    title: '执行保障机制',
    subtitle: '确保明年计划落地',
    component: 'action-plan',
    section: '结论',
    revealSteps: 2,
    duration: 60,
    presenterNotes: '明年执行保障机制：周报追踪/月度复盘/季度调整，异常预警机制。',
  },
];

export const opsDirectorScene: SceneConfig = {
  id: 'ops-director',
  label: '运营总监汇报',
  description: '向运营总监汇报，执行层面，聚焦运营细节与资源需求',
  icon: 'BarChart3',
  availableTimeframes: ['daily', 'weekly', 'monthly', 'quarterly', 'yearly'],
  slides: {
    daily,
    weekly,
    monthly,
    quarterly,
    yearly,
  },
};
